create table measurements (
                              raining boolean,
                              value float(53),
                              id bigint generated by default as identity,
                              sensor_id bigint,
                              time timestamp(6),
                              primary key (id)
);
create table sensors (
                         id bigint generated by default as identity,
                         name varchar(255),
                         primary key (id)
);
create table users (
                       id bigint generated by default as identity,
                       password varchar(255),
                       username varchar(255),
                       primary key (id)
);
alter table if exists measurements
    add constraint FKel3lbehitykut0jocq49tg1s9
    foreign key (sensor_id)
    references sensors;